# Generated by Django 4.0 on 2021-12-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apod', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apods',
        ),
        migrations.AddField(
            model_name='user',
            name='apods',
            field=models.ManyToManyField(blank=True, null=True, to='apod.Apod'),
        ),
    ]
