# Generated by Django 4.0 on 2021-12-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apod', '0001_initial'),
        ('users', '0002_remove_user_apods_user_apods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apods',
            field=models.ManyToManyField(blank=True, to='apod.Apod'),
        ),
    ]
