# Generated by Django 4.0 on 2021-12-27 19:57

import apod.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apod',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(help_text='Date for an APOD', primary_key=True, serialize=False)),
                ('json_data', models.JSONField()),
            ],
            bases=(models.Model, apod.models.GetReversedURL),
        ),
    ]
