# Generated by Django 4.0 on 2021-12-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apod',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apod/apod_data/images/'),
        ),
    ]
